#!/bin/bash
echo "getting commit ID"
ID=$(git rev-parse HEAD)
echo $ID
PR_NUMBER=$(docker run --rm nalbina/jq sh -c "curl https://api.github.com/repos/codebuddies/codebuddies/pulls | jq '.[]  | select(.head.sha == \"$ID\") | .number'")
RECENT_ID=$(docker images -q | sed -n 2p)
echo $PR_NUMBER
if [ -n "$PR_NUMBER" ]; then
    docker tag $RECENT_ID codebuddiesdotorg/codebuddies:PR_$PR_NUMBER   
    docker push codebuddiesdotorg/codebuddies:PR_$PR_NUMBER
fi